# Generated by Django 4.2.5 on 2023-10-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user',
            name='Useraddress',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='registered_user',
            name='Usersex',
            field=models.CharField(default='M', max_length=2),
        ),
    ]
