# Generated by Django 4.0.4 on 2023-10-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_registered_user_useraddress_registered_user_usersex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_user',
            name='Passwd',
            field=models.CharField(max_length=128),
        ),
    ]
