# Generated by Django 4.2.5 on 2023-10-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0004_pageview_productmodel_ordersmodel_detailmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='pdescription',
            new_name='pdescription1',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='pimages',
            new_name='pimage1',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pcolor1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pcolor2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pcolor3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pdescription2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pimage2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pimage3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pimage4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pimage5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pimage6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pimage7',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pimage8',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='psizeL',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='psizeM',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='psizeS',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='psizeXL',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pstock',
            field=models.IntegerField(default=0),
        ),
    ]
