# Generated by Django 4.0.4 on 2023-10-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0005_rename_pdescription_productmodel_pdescription1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailmodel',
            old_name='pname',
            new_name='dname',
        ),
        migrations.RenameField(
            model_name='detailmodel',
            old_name='quantity',
            new_name='dquantity',
        ),
        migrations.RenameField(
            model_name='detailmodel',
            old_name='shipping_fee',
            new_name='dshipping_fee',
        ),
        migrations.RenameField(
            model_name='detailmodel',
            old_name='unitprice',
            new_name='dunitprice',
        ),
        migrations.AddField(
            model_name='detailmodel',
            name='dcolor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='detailmodel',
            name='dsize',
            field=models.CharField(default='', max_length=20),
        ),
    ]
