# Generated by Django 4.2.5 on 2023-10-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0006_rename_pname_detailmodel_dname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccategory', models.CharField(max_length=50, unique=True, verbose_name='商品分類')),
            ],
        ),
    ]
