# Generated by Django 4.2.5 on 2023-10-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0007_categorymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
