# Generated by Django 4.2.5 on 2023-10-29 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0008_delete_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('ColorID', models.AutoField(primary_key=True, serialize=False, verbose_name='顏色ID')),
                ('ColorName', models.CharField(max_length=50, verbose_name='顏色名稱')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTypeModel',
            fields=[
                ('TypeID', models.AutoField(primary_key=True, serialize=False, verbose_name='分類ID')),
                ('TypeName', models.CharField(max_length=50, verbose_name='分類名稱')),
            ],
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('SizeID', models.AutoField(primary_key=True, serialize=False, verbose_name='尺寸ID')),
                ('SizeName', models.CharField(max_length=50, verbose_name='尺寸名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('ProductName', models.CharField(default='', max_length=100, verbose_name='商品名稱')),
                ('Price', models.IntegerField(default=0, verbose_name='價格')),
                ('Type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_app.producttypemodel', verbose_name='分類ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorSizeStockModel',
            fields=[
                ('InventoryID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.PositiveIntegerField(default=0, verbose_name='庫存')),
                ('Color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_app.colormodel', verbose_name='顏色ID')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_app.products', verbose_name='商品ID')),
                ('Size_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_app.sizemodel', verbose_name='尺寸ID')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('ImageID', models.AutoField(primary_key=True, serialize=False, verbose_name='圖片ID')),
                ('ImageName', models.CharField(max_length=100, verbose_name='圖片名稱')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_app.products', verbose_name='商品ID')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionModel',
            fields=[
                ('DescriptionID', models.AutoField(primary_key=True, serialize=False, verbose_name='敘述ID')),
                ('Description', models.TextField(verbose_name='敘述')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_app.products', verbose_name='商品ID')),
            ],
        ),
    ]
