# Generated by Django 4.2.5 on 2023-10-29 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0009_colormodel_producttypemodel_sizemodel_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionmodel',
            name='Product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='shopping_app.products', verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='Product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopping_app.products', verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='productcolorsizestockmodel',
            name='Color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcolorsizestocks', to='shopping_app.colormodel', verbose_name='顏色ID'),
        ),
        migrations.AlterField(
            model_name='productcolorsizestockmodel',
            name='Product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcolorsizestocks', to='shopping_app.products', verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='productcolorsizestockmodel',
            name='Size_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcolorsizestocks', to='shopping_app.sizemodel', verbose_name='尺寸ID'),
        ),
    ]
