# Generated by Django 4.0.4 on 2023-11-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0010_alter_descriptionmodel_product_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
        migrations.RemoveField(
            model_name='detailmodel',
            name='dshipping_fee',
        ),
    ]
