# Generated by Django 4.0.4 on 2023-11-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0011_delete_productmodel_remove_detailmodel_dshipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user',
            name='Isblacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
